name: climaax_scenarios

channels:
    - conda-forge

dependencies:
    - ipykernel=6.29.5
    - ipython=8.27.0
    - ipywidgets=8.1.3
    - jupyterlab-myst=2.4.2
    - jupyterlab=4.2.3
    - notebook=7.2.1
    - numpy=1.26.4
    - pandas=2.2.2
    - pip
    - plotly=5.22.0
    - python=3.11
